name: 2. Aggregate Final Rules (8:00 AM)

on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 00:00 运行 (北京时间 8:00)
    - cron: "0 0 * * *"

jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Aggregate all rules
        env:
          GITHUB_USER: ${{ github.repository_owner }}
        run: |
          # ad-rules.list
          (
            echo "! Title: My Custom Ad Rules (Aggregated)"
            echo "! Author: $GITHUB_USER"
            echo "! Last Updated: $(date -u --iso-8601=seconds)"
            echo "! Homepage: https://github.com/$GITHUB_USER/${{ github.event.repository.name }}"
            echo ""
            (
              # 直接读取生成的本地文件
              cat generated/converted-ad-rules.list
              # 其他外部源
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/PCDN.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/MyBlockAds.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/RejectAd.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/AdRules.list"
              curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising.list"
            ) | grep -vE '^!|^#|^$' | sort -u
          ) > ad-rules.list

          # direct-rules.list
          (
            echo "! Title: My Custom Direct Rules (Aggregated)"
            echo "! Author: $GITHUB_USER"
            echo "! Last Updated: $(date -u --iso-8601=seconds)"
            echo "! Homepage: https://github.com/$GITHUB_USER/${{ github.event.repository.name }}"
            echo ""
            (
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/Apple.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/Media-Direct"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/Media-Proxy.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/KeleeOne/Loon/Rule/ChinaMax.list"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/Lan"
              curl -sL "https://raw.githubusercontent.com/sooyaaabo/Loon/main/Rule/CN_REGION"
            ) | grep -vE '^!|^#|^$' | sort -u
          ) > direct-rules.list

      - name: Commit and Push final lists
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ad-rules.list direct-rules.list
          if ! git diff --staged --quiet; then
            git commit -m "feat(rules): 自动更新聚合规则列表"
            git push
          else
            echo "No changes in final rules. Nothing to push."
          fi
